### ISSUE TITLE
Windows Build: Failed to load library (ErrorCode: 193)

### ISSUE THREAD

**Issue by lazydevyo** [Scorr/RetroUnity#25]
```
LoadCore: D:/Google Drive/NEm/v4/NEm_Data/StreamingAssets\libwinpthread-1.dll
Failed to load library (ErrorCode: 193)
LoadCore: D:/Google Drive/NEm/v4/NEm_Data/StreamingAssets\snes9x_libretro.dll
Failed to load library (ErrorCode: 193)
```

On editor works normally.
Unity version 2019.4.9f1

**Comment by lazydevyo** [comment]
Similar problem on Android 
```
LoadCore: snes9x_libretro_android.so
dlopen failed: library "snes9x_libretro_android.so" not found
```

**Comment by lazydevyo** [comment]
> Similar problem on Android
> 
> ```
> LoadCore: snes9x_libretro_android.so
> dlopen failed: library "snes9x_libretro_android.so" not found
> ```

Renaming snes9x_libretro.so to snes9x_libretro_android.so at the streaming, folder fixes the issue but now it cannot find the rom,
`DirectoryNotFoundException: Could not find a part of the path "/jar:file:/data/app/com.Nem.NEm-OXwFeBTb--Zt_q-vKl7hQg==/base.apk!/assets/F-Zero.smc".` (Rom exist in the streaming folder before building)

**Comment by Skurdt** [comment]
For the windows bit, the editor runs in 64bit mode. If you build for 32bit and try to load the same 64bit cores you used for the editor they won't load. Either download 32bit (x86) cores for your build or build your Unity project targeting 64bit (x86_64).

**Comment by lazydevyo** [comment]
You actually correct, I actually googled it and found it was related to the architecture. but it didn't come in to my mind that Unity editor and build was on a different setting. Resolved!
